// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int times = Integer.parseInt(args[0]);
		int big = 0;
		int small = 0;

		while (times > 0) {
			double number = Math.random();
				if (number > 0.5) {
					big += 1;
				}
				else {
					small += 1;
				}
				times -= 1;
		}
		System.out.println("> 0.5: " + big + "times");
		System.out.println("<= 0.5: " + small + "times");

		if (small != 0 && big != 0) {
			double max = 1.0 * Math.max(small, big);
			double min = 1.0 * Math.min(small, big);
			System.out.println("ratio: " + min/max);
		}

	}
}
